version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 5
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 5
    labels:
      - dependencies
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 5
    labels:
      - dependencies
