services:
  unified-store-notifier:
    container_name: unified-store-notifier
    hostname: unified-store-notifier
    build: .
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
